language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

matrix:
  allow_failures:
    - python: '3.4'
    - python: '3.5'
    - python: '3.6'
  fast_finish: true

before_install:
  - python -m pip install -q --upgrade pip
  - python -m pip install lalsuite
  - python -m pip install -r requirements.txt

install:
  - python -m pip install .

script:
  # run unit tests
  - python setup.py test
  # run --help on all scripts (just to check for missing imports, etc)
  - |
    set -e
    for EXE in bin/*; do
        echo "$ `basename $EXE` --help"
        `basename $EXE` --help 1> /dev/null
    done
    set +e

cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
