language: python
dist: xenial

python:
  - '3.5'
  - '3.6'
  - '3.7'

before_install:
  - python -m pip install -q --upgrade pip
  - python -m pip install -r requirements.txt

install:
  - python -m pip install .

script:
  # run flake8
  - python -m flake8 gwvet/**/*.py
  - python -m flake8 bin/*
  # test executables
  - python -m coverage run --append $(which gwvet) --help
  - python -m coverage run --append $(which gwvet-hug) --help
  - python -m coverage run --append $(which gwvet-vdf) --help

cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
