language: python
dist: xenial

python:
  - '3.5'
  - '3.6'
  - '3.7'

before_install:
  - python -m pip install -q --upgrade pip
  - python -m pip install lalsuite
  - python -m pip install -r requirements.txt

install:
  - python -m pip install .

script:
  # run flake8
  - python -m flake8 gwvet/**/*.py
  - python -m flake8 bin/*
  # run --help on all scripts (just to check for missing imports, etc)
  - |
    set -e
    for EXE in bin/*; do
        echo "$ $(basename $EXE) --help"
        $(basename $EXE) --help 1> /dev/null
    done
    set +e

cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
